apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: resources
  namespace: argocd
spec:
  sources:
    - repoURL: "https://github.com/roscoejp/gitops-samples.git"
      targetRevision: main
      ref: values_repo
    - path: charts/bucket-resource
      repoURL: "https://github.com/roscoejp/gitops-samples.git"
      targetRevision: main
      helm:
        valuesFiles:
          - $values_repo/values/bucket-values.yaml
    - path: charts/database-resource
      repoURL: "https://github.com/roscoejp/gitops-samples.git"
      targetRevision: main
      helm:
        valuesFiles:
          - $values_repo/values/database-values.yaml
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
