apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoac-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - ref: values
      repoURL: "https://github.com/roscoejp/gitops-samples.git"
      targetRevision: apps-in-helm
    - helm:
        releaseName: operators
        valueFiles:
          - $values/gitops/argocd/app-of-appcharts/operators.yaml
      path: charts/argocd-applications
      repoURL: "https://github.com/roscoejp/gitops-samples.git"
      targetRevision: apps-in-helm
    - helm:
        releaseName: applications
        valueFiles:
          - $values/gitops/argocd/app-of-appcharts/applications.yaml
      path: charts/argocd-applications
      repoURL: "https://github.com/roscoejp/gitops-samples.git"
      targetRevision: apps-in-helm
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
