apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoac-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: "https://github.com/roscoejp/gitops-samples.git"
      path: gitops/argocd/app-of-appcharts
      targetRevision: apps-in-helm
    - ref: values
      repoURL: "https://github.com/roscoejp/gitops-samples.git"
      targetRevision: apps-in-helm
    - repoURL: "https://github.com/roscoejp/gitops-samples.git"
      path: charts/argocd-applications
      targetRevision: apps-in-helm
      helm:
        valueFiles:
          - $values/gitops/argocd/app-of-appcharts/operators.yaml
        releaseName: operators
    - repoURL: "https://github.com/roscoejp/gitops-samples.git"
      path: charts/argocd-applications
      targetRevision: apps-in-helm
      helm:
        valueFiles:
          - $values/gitops/argocd/app-of-appcharts/applications.yaml
        releaseName: applications
